### ISSUE TITLE
HTTP response error using wrong HTTP status type

### ISSUE THREAD

**Issue by acusworth** [micronaut-projects/micronaut-problem-json#32]
# Steps to Reproduce

1. Create a simple controller
2. Create an Exception handler to map thrown exceptions to error responses
3. Throw a `Problem` using a status other than HTTP 500

```java
throw Problem.builder()
       .withTitle("Not Found")
       .withStatus(new HttpStatusType(HttpStatus.NOT_FOUND))
       .withDetail("The requested entity was not found.")
       .withType(URI.create( "https://example.com/errors/not-found"))
       .build();
```

# Expected Behaviour

When building a `Problem` the set status should be the returned HTTP status.

```
HTTP/1.1 404 Not Found
Content-Type: application/problem+json

{
type":"https://example.com/errors/not-found",
"title":"Not Found",
"status":404,
"detail":"Requested entity abc123 is not found."
}
```

# Actual Behaviour

Regardless of the set status type, the HTTP status returns as 500, the body does show the correct status type.

```
HTTP/1.1 500 Internal Server Error
Content-Type: application/problem+json

{
type":"https://example.com/errors/not-found",
"title":"Not Found",
"status":404,
"detail":"Requested entity abc123 is not found."
}
```

Stacktrace from event:
```shell
2021-06-30 11:27:58 - io.micronaut.http.server.netty.RoutingInBoundHandler - Unexpected error occurred: Not Found: Requested entity abc123 is not found. timestamp=1625066878769546000 trace_id=42b2784c24e82f87d006952e0861e6a1 span_id=30f3f2348307cb89
org.zalando.problem.DefaultProblem: Not Found: Requested entity abc123 is not found.
        at org.zalando.problem.ProblemBuilder.build(ProblemBuilder.java:83) ~[problem-0.25.0.jar:?]
        at com.example.exception.handler.EntityNotFoundExceptionHandler.handle(EntityNotFoundExceptionHandler.java:37) ~[main/:?]
        at com.example.exception.handler.EntityNotFoundExceptionHandler.handle(EntityNotFoundExceptionHandler.java:26) ~[main/:?]
        at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$exceptionCaughtInternal$1(RoutingInBoundHandler.java:379) ~[micronaut-http-server-netty-2.5.7.jar:2.5.7]
        at io.reactivex.internal.operators.flowable.FlowableFromCallable.subscribeActual(FlowableFromCallable.java:39) [rxjava-2.2.10.jar:?]
        at io.reactivex.Flowable.subscribe(Flowable.java:14918) [rxjava-2.2.10.jar:?]
        at io.reactivex.Flowable.subscribe(Flowable.java:14865) [rxjava-2.2.10.jar:?]
        at io.micronaut.reactive.rxjava2.RxInstrumentedFlowable.subscribeActual(RxInstrumentedFlowable.java:57) [micronaut-runtime-2.5.7.jar:2.5.7]
        at io.reactivex.Flowable.subscribe(Flowable.java:14918) [rxjava-2.2.10.jar:?]
        at io.reactivex.Flowable.subscribe(Flowable.java:14868) [rxjava-2.2.10.jar:?]
        at io.micronaut.http.server.netty.RoutingInBoundHandler.exceptionCaughtInternal(RoutingInBoundHandler.java:383) [micronaut-http-server-netty-2.5.7.jar:2.5.7]
        at io.micronaut.http.server.netty.RoutingInBoundHandler.access$200(RoutingInBoundHandler.java:151) [micronaut-http-server-netty-2.5.7.jar:2.5.7]
        at io.micronaut.http.server.netty.RoutingInBoundHandler$5.doOnError(RoutingInBoundHandler.java:1408) [micronaut-http-server-netty-2.5.7.jar:2.5.7]
        at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onError(CompletionAwareSubscriber.java:63) [micronaut-core-reactive-2.5.7.jar:2.5.7]
        at io.micronaut.http.server.netty.RoutingInBoundHandler.emitRouteResponse(RoutingInBoundHandler.java:1664) [micronaut-http-server-netty-2.5.7.jar:2.5.7]
        at io.micronaut.http.server.netty.RoutingInBoundHandler.access$2100(RoutingInBoundHandler.java:151) [micronaut-http-server-netty-2.5.7.jar:2.5.7]
        at io.micronaut.http.server.netty.RoutingInBoundHandler$6$1.request(RoutingInBoundHandler.java:1469) [micronaut-http-server-netty-2.5.7.jar:2.5.7]
        at io.micronaut.http.server.netty.async.ContextCompletionAwareSubscriber.doOnSubscribe(ContextCompletionAwareSubscriber.java:49) [micronaut-http-server-netty-2.5.7.jar:2.5.7]
        at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onSubscribe(CompletionAwareSubscriber.java:38) [micronaut-core-reactive-2.5.7.jar:2.5.7]
        at io.micronaut.http.server.netty.RoutingInBoundHandler$6.doSubscribe(RoutingInBoundHandler.java:1457) [micronaut-http-server-netty-2.5.7.jar:2.5.7]
        at io.micronaut.http.server.netty.RoutingInBoundHandler$6.subscribe(RoutingInBoundHandler.java:1448) [micronaut-http-server-netty-2.5.7.jar:2.5.7]
        at io.micronaut.http.server.netty.RoutingInBoundHandler.executeRoute(RoutingInBoundHandler.java:1119) [micronaut-http-server-netty-2.5.7.jar:2.5.7]
        at io.micronaut.http.server.netty.RoutingInBoundHandler.handleRouteMatch(RoutingInBoundHandler.java:775) [micronaut-http-server-netty-2.5.7.jar:2.5.7]
        at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:606) [micronaut-http-server-netty-2.5.7.jar:2.5.7]
        at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:148) [micronaut-http-server-netty-2.5.7.jar:2.5.7]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:102) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:200) [micronaut-http-netty-2.5.7.jar:2.5.7]
        at io.micronaut.http.netty.stream.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:123) [micronaut-http-netty-2.5.7.jar:2.5.7]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-codec-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64) [netty-codec-http-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:200) [netty-handler-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:162) [netty-handler-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.opentelemetry.javaagent.instrumentation.netty.v4_1.server.HttpServerRequestTracingHandler.channelRead(HttpServerRequestTracingHandler.java:38) [?:?]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-codec-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-codec-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-transport-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.64.Final.jar:4.1.64.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.64.Final.jar:4.1.64.Final]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

# Environment Information

- **Operating System**: Mac OS 11
- **Micronaut Version:** 2.5.7
- **JDK Version:** Zulu Java 11

**Comment by sdelamo** [comment]
@acusworth  Sorry, I am unable to reproduce the issue. 

I have added a test for your description and it passes. I am closing the issue. 

If you can upload a reproducible sample project, I will reopen it.
